### ISSUE TITLE
Decide on primary title as moderator

### ISSUE THREAD

**Issue by joliedielemans** [course-dprep/Investigating-IMDB-data#7]
_How are we going to use this as moderator and how are we going to decide how popular a certain title is?_ How should we use it in R? Which command to use?

- primaryTitle (string) – the more popular title / the title used by the filmmakers on promotional materials at the point of release 

@hannesdatta

**Comment by hannesdatta** [comment]
I think you need to find a way to measure popularity. I struggle to see how you can use a string title as a proxy for popularity.

**Comment by hannesdatta** [comment]
Try to think a bit more about it. What is it exactly that you want to measure? Can you measure it with the data that you have?
